name: Validate Tested Up To Version
on:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  pull-requests: write
  contents: write

jobs:
  validate-plugin-version:
    runs-on: ubuntu-latest
    name: Validate Plugin Tested Up To
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
      - uses: jazzsequence/action-validate-plugin-version@33b0e43e436229825afc8427b19829a0c9aea498 # v2.0.0
        branch: 'develop'
