name: Validate Tested Up To Version
on:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  pull-requests: write
  contents: write

jobs:
  validate-plugin-version:
    runs-on: ubuntu-latest
    name: Validate Plugin Tested Up To
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0
      - uses: jazzsequence/action-validate-plugin-version@33b0e43e436229825afc8427b19829a0c9aea498 # v2.0.0
        with:
          branch: 'develop'
